version: '3.3'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: "keycloak"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - auth

  keycloak:
    image: jboss/keycloak:4.8.3.Final
    restart: always
    depends_on:
      - postgres
    ports:
      - 8443:8443
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: "postgres"
      DB_PASSWORD: ${POSTGRESQL_PASSWORD}
      JDBC_PARAMS: "connectTimeout=30"
      DB_ADDR: "postgres"
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    networks:
      - auth

  reverse-proxy:
    build:
      context: ./src
      dockerfile: Dockerfile-dev
    ports:
      - $SERVICE_PORT:$SERVICE_PORT
    restart: always
    environment:
      JWT_SECRET: $JWT_SECRET
      SONG_SERVICE: $SONG_SERVICE
      SCORE_SERVICE: "placeholder"
      SERVICE_PORT: $SERVICE_PORT
      ADMIN_ROLE: $ADMIN_ROLE
    volumes:
      - ./src:/opt/app
    networks:
      - auth
      - $SONG_DOCKER_NETWORK

  integration-tests:
    build: ./integration_tests
    environment:
        KEYCLOAK_AUTH_URL: "https://keycloak:8443/auth/realms/clin"
        KEYCLOAK_CLIENT_ID: "clin-proxy-api"
        KEYCLOAK_CLIENT_SECRET: $JWT_SECRET
        KEYCLOAK_USERNAME: "test"
        KEYCLOAK_PASSWORD: "testtest"
    networks:
      - auth



networks:
  auth:
  overture-dev_overture:
    external: true