version: '3.3'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: "keycloak"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - auth

  keycloak:
    image: jboss/keycloak:4.8.3.Final
    restart: always
    depends_on:
      - postgres
    ports:
      - 8443:8443
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: "postgres"
      DB_PASSWORD: ${POSTGRESQL_PASSWORD}
      JDBC_PARAMS: "connectTimeout=30"
      DB_ADDR: "postgres"
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    networks:
      - auth

  reverse-proxy:
    build: .
    ports:
      - 8080:8080
    restart: always
    environment:
      JWT_SECRET: "01b99f28-1331-4fec-903b-c2e8043cec77"
      SONG_SERVICE: "placeholder"
      SCORE_SERVICE: "placeholder"
      SERVICE_PORT: 8080
    networks:
      - auth

  integration-tests:
    build: ./integration_tests
    environment:
        KEYCLOAK_AUTH_URL: "https://keycloak:8443/auth/realms/clin"
        KEYCLOAK_CLIENT_ID: "clin-proxy-api"
        KEYCLOAK_CLIENT_SECRET: "01b99f28-1331-4fec-903b-c2e8043cec77"
        KEYCLOAK_USERNAME: "test"
        KEYCLOAK_PASSWORD: "testtest"
    networks:
      - auth



networks:
  auth: